---
- hosts: my_servers
  become: yes

  pre_tasks:
    - name: Обновление списка пакетов
      apt:
        update_cache: yes

  vars:
    ansible_python_interpreter: /usr/bin/python3.12
  
  roles:
    - nginx
    - certificates
